---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: /Users/payton-jones/Google Drive/99 - Other/Curriculum Vitae/svm-latex-cv.tex
geometry: margin=1in

title: "Curriculum Vitae"
author: PAYTON J. JONES
jobtitle: 
address: 
web: 

email: paytonjjones@gmail.com
phone: "425-367-2939"

keywords: curriculum vitae, Rmarkdown, CV, resume, R, psychology, machine learning, data science, network analysis

fontawesome: no
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 12pt
linkcolor: black
urlcolor: black
---

# EDUCATION

__Experimental Psychopathology, PhD__ \hfill 2016-2021 | Cambridge, MA  
Harvard University  

* National Science Foundation Graduate Research Fellow
* Dissertation - The Neurotic Treadmill: Decreasing Adversity, Increasing Vulnerability 

<!-- GPA: 3.88 -->

__Psychology, MA__ \hfill 2016-2018 | Cambridge, MA  
Harvard University  

* Thesis - Bridge Centrality: A Network Approach to Comorbidity 

__Psychology, BS__ \hfill 2011-2016 | Provo, UT  
Brigham Young University

* GPA: 4.0, Summa Cum Laude
* GRE: Verbal 169 (99%), Quantitative 168 (95%), Writing 5.5 (98%)

<!-- * Psi Chi Presidency
* Portuguese Language Certificate, Mastery Level -->

# PEER-REVIEWED JOURNAL ARTICLES

35\. __Jones, P. J.__. (in press). What’s in a trauma? Using machine learning to unpack what makes an event traumatic. _Journal of Affective Disorders._

34\. __Jones, P. J.__, Levari, D. E., Bellet, B. W., & McNally, R. J. (in press). Exposure to descriptions of traumatic events narrows one’s concept of trauma. _Journal of Experimental Psychology: Applied._

33\. __Jones, P. J.__ & McNally, R. J. (in press). Does broadening one's concept of trauma undermine resilience? _Psychological Trauma: Theory, Research, Practice, and Policy._ https://doi.org/10.1037/tra0001063

32\. __Jones, P. J.__, Bellet, B. W., Levari, D. E., & McNally, R. J. (in press). Psychological response data on the traumatic nature of 600 written events. _Journal of Open Psychology Data._

31\. Guineau, M. G., __Jones, P. J.__, Bellet, B. W., & McNally, R. J. (in press). A network analysis of DSM-5 posttraumatic stress disorder symptoms and trauma centrality. _Journal of Traumatic Stress._

30\. Peters, J., Bellet, B. W., __Jones, P. J.__, Wu, G. W. Y., Wang, L., & McNally, R. J. (in press). Posttraumatic stress or posttraumatic growth? Using network analysis to explore the relationships between coping styles and trauma outcomes. _Journal of Anxiety Disorders._

29\. __Jones, P. J.__, Mair, P., Simon, T., & Zeileis, A. (2020). Network trees: A method for recursively partitioning covariance structures. _Psychometrika. 85_, 926-945. https://doi.org/10.1007/s11336-020-09731-4

28\. Moriarity, D., Bart, C., Stumper, A., __Jones, P. J.__, & Alloy, L. (2020). Mood symptoms and impairment due to substance use: A network perspective on comorbidity. _Journal of Affective Disorders._ https://doi.org/10.1016/j.jad.2020.09.086

27\. __Jones, P. J.__, Williams, D. R., & McNally, R. J. (2020). Sampling variability is not nonreplication: A Bayesian reanalysis of Forbes, Wright, Markon, & Krueger. _Multivariate Behavioral Research._ https://doi.org/10.1080/00273171.2020.1797460

26\. Iverson, G. L., __Jones, P. J.__, Karr, J. E., Maxwell, B., Zafonte, R., Berkner, P. D., & McNally, R. J. (2020). Network structure of physical, cognitive, and emotional symptoms at preseason baseline in student athletes with attention-deficit hyperactivity disorder. _Archives of Clinical Neuropsychology._ https://doi.org/10.1093/arclin/acaa030

25\. Peckham, A. D., __Jones, P. J.__, Snorrason, I., Wessman, I., Björgvinsson, T., & Beard, C. (2020). Age-related changes in borderline personality disorder symptom networks in a transdiagnostic sample. _Journal of Affective Disorders._ https://doi.org/10.1016/j.jad.2020.05.111

24\. Smith, A. R., Forrest, L. N., Duffy, M. E., __Jones, P. J.__, Joiner, T. E., & Pisetsky, E. M. (2020). Identifying bridge pathways between eating disorder symptoms and suicidal ideation across three samples. _Journal of Abnormal Psychology._ https://doi.org/10.1037/abn0000553

23\. Iverson, G. L., __Jones, P. J.__, Karr, J. E., Maxwell, B., Zafonte, R., Berkner, P. D., & McNally, R. J. (2020). Architecture of physical, cognitive, and emotional symptoms at preseason baseline in adolescent student athletes with a history of mental health problems. _Frontiers in Neurology. 11_, 175. https://doi.org/10.3389/fneur.2020.00175

22\. __Jones, P. J.__, Bellet, B. W., & McNally, R. J. (2020). Helping or harming? The effect of trigger warnings on individuals with trauma histories. _Clinical Psychological Science._ https://doi.org/10.1177/2167702620921341

21\. Bellet, B. W., __Jones, P. J.__, Meyersburg, C., Brenneman, M., Morehead, K., & McNally, R. J. (2020). Trigger warnings and resilience in college students: A preregistered replication and extension. _Journal of Experimental Psychology: Applied. 26_, 717-723. https://doi.org/10.1037/xap0000270

20\. Bellet, B. W., __Jones, P. J.__, & McNally, R. J. (2020). Self-triggering? An exploration of individuals who seek reminders of trauma. _Clinical Psychological Science_. https://doi.org/10.1177/2167702620917459

19\. Lefevor, G. T., Park, S. Y., Acevedo, M. J., & __Jones, P. J.__ (2020). Sexual orientation complexity and psychosocial/health outcomes. _Journal of Homosexuality._

18\. Wasil, A., Venturo-Conerly, K. Shinde, S., Patel, V., & __Jones, P. J.__ (2020). Applying network analysis to understand depression and substance use in Indian adolescents. _Journal of Affective Disorders. 265_, 278-286. https://doi.org/10.1016/j.jad.2020.01.025

17\. Summers, B. J., Aalbers, G., __Jones, P. J.__, McNally, R. J., Phillips, K. A., & Wilhelm, S. (2020). A network perspective on body dysmorphic disorder and major depressive disorder. _Journal of Affective Disorders. 262_, 165-173. https://doi.org/10.1016/j.jad.2019.11.011

16\. Robinaugh, D. R., Brown, M. L., Losiewicz, O., __Jones, P. J.__, Marques, L., & Baker, A. W. (2020). Toward a precision psychiatry approach to treating anxiety disorders with ecological momentary assessment: The example of panic disorder. _General Psychiatry. 33_, e100161. https://doi.org/10.1136/gpsych-2019-100161

15\. Meier, M., Kossakowski, J. J., __Jones, P. J.__, Riemann, B. C., Kay, B., & McNally, R. J. (2020). Obsessive-compulsive symptoms in eating disorders: A network investigation. _International Journal of Eating Disorders. 53_(3), 362-371.  https://doi.org/10.1002/eat.23196

14\. Mancini, A. D., Littleton, H. L., Grills, A. E., & __Jones, P. J.__ (2019). PTSD near and far: Symptom networks from two to 12 months after the Virginia Tech campus shootings. _Clinical Psychological Science. 7_(6), 1340-1354. https://doi.org/10.1177/2167702619859333

13\. Elliott, H., __Jones, P. J.__, & Schmidt, U. (2019). Central symptoms predict post-treatment outcomes and clinical impairment in anorexia nervosa: A network analysis. _Clinical Psychological Science._ https://doi.org/10.1177/2167702619865958

12\. __Jones, P. J.__, Ma, R., & McNally, R. J. (2019). Bridge centrality: A network approach to understanding comorbidity. _Multivariate Behavioral Research._ https://doi.org/10.1080/00273171.2019.1614898

11\. __Jones, P. J.__, Mair, P., Kuppens, S., & Weisz, J. R. (2019). An upper limit to youth psychotherapy benefit? A meta-analytic copula approach to psychotherapy outcomes. _Clinical Psychological Science._ https://doi.org/10.1177/2167702619858424

10\. __Jones, P. J.__, Mair, P., & McNally, R. J. (2018). Visualizing psychological networks: A tutorial in R. _Frontiers in Psychology. 9_, 1742. https://doi.org/10.3389/fpsyg.2018.01742

9\. Wang, S. B., __Jones, P. J.__, Dreier, M., Elliott, H., & Grilo, C. M. (2018). Core psychopathology of treatment-seeking patients with binge-eating disorder: A network analysis investigation. _Psychological Medicine. 49_(11), 1923-1928. https://doi.org/10.1017/s0033291718002702

8\. Bellet, B. W., __Jones, P. J.__, & McNally, R. J. (2018). Trigger warning: Empirical evidence ahead. _Journal of Behavior Therapy and Experimental Psychiatry. 61_, 134-141. https://doi.org/10.1016/j.jbtep.2018.07.002

7\. __Jones, P. J.__, Park, S.Y., & Lefevor, G. T. (2018). Contemporary college student anxiety: The role of academic distress, financial stress, and support. _Journal of College Counseling. 21_, 252-264. https://doi.org/10.1002/jocc.12107

6\. Heeren, A., __Jones, P.J.__, & McNally, R.J. (2018). Mapping network connectivity among symptoms of social anxiety and comorbid depression in people with social anxiety disorder. _Journal of Affective Disorders. 228_, 75-82. https://doi.org/10.1016/j.jad.2017.12.003

5\. Levinson, C. A., Brosof, L. C., Vanzhula, I. Christian, C., __Jones, P. J.__, Rodebaugh, T. L., Langer, J. K., White, E. K., Warren, C., Weeks, J. W., Menatti, A., Lim, M. H., & Fernandez, K. C. (2018). Social anxiety and eating disorder comorbidity and underlying vulnerabilities: Using network analysis to conceptualize comorbidity. _International Journal of Eating Disorders  51_(7), 693-709. https://doi.org/10.1002/eat.22890

4\. Forrest, L. N., __Jones, P. J.__, Ortiz, S. N., & Smith, A. (2018). Core psychopathology in anorexia nervosa and bulimia nervosa: A network analysis. _International Journal of Eating Disorders. 51_(7), 668-679. https://doi.org/10.1002/eat.22871

3\. Bellet, B. W., __Jones, P. J.__, Neimeyer, R. A., & McNally, R. J. (2018). Bereavement outcomes as causal systems: A network analysis of the co-occurrence of complicated grief and posttraumatic growth. _Clinical Psychological Science. 6_(6), 797-809. https://doi.org/10.1177/2167702618777454

2\. __Jones, P. J.__, Mair, P., Mugno, B. L., Riemann, B. C. & McNally, R. J. (2018). A network perspective on comorbid OCD and depression in adolescents. _Journal of Anxiety Disorders. 53_, 1-8. https://doi.org/10.1016/j.janxdis.2017.09.008

1\. __Jones, P. J.__, Heeren, A., & McNally, R.J. (2017). Commentary: A network theory of mental disorders. _Frontiers in Psychology. 8_, 1305. https://doi.org/10.3389/fpsyg.2017.01305 

# GRANTS & FELLOWSHIPS

__National Science Foundation__, Graduate Research Fellowship, $138,000 \hfill 2018-2021 

__Mind, Brain, & Behavior Initiative__, Graduate Student Awards (2), $5,115 \hfill 2018

__Harvard University__, Talley Award, $3,500, \hfill 2018

__Harvard University__, Karen Stone Fellowship, $64,000 \hfill 2016-2018

# STATISTICAL SOFTWARE

3\. __Jones, P. J.__, Simon, T., Zeileis, A., & Mair, P. (2019). networktree: Recursive partitioning of network models. _R package version 0.2.2._ https://CRAN.R-project.org/package=networktree

2\. van Borkulo, C., Epskamp, S., & __Jones, P. J.__ (2019). NetworkComparisonTest: Statistical comparison of two networks based on three invariance measures. _R package version 2.2.1._ https://CRAN.R-project.org/package=NetworkComparisonTest

1\. __Jones, P. J.__ (2017). networktools: Assorted tools for identifying important nodes in networks. _R package version 1.2.0._ https://CRAN.R-project.org/package=networktools


# ACADEMIC PRESENTATIONS

_* = panel chair_

21\. __Jones, P. J.__*, Williams, D. R., & McNally, R. J. (2020). Evaluating the sampling variability and replicability of network comorbidity. Symposium at the Association for Behavioral and Cognitive Therapies (ABCT) Convention, Virtual Convention. 

20\. __Jones, P. J.__ (2019). Trigger warnings and the neurotic treadmill: Does it matter if we expand the definition of violence? Symposium at the Association for Behavioral and Cognitive Therapies (ABCT) Convention, Atlanta, GA.

19\. __Jones, P. J.__ (2019). Sticks and stones: Investigating the belief that words can harm. Presentation at the Annual Meeting of the Foundation of Individual Rights in Education, Boston, MA.

18\. Smith, A. R., Forrest, L. N., Duffy, M. __Jones, P. J.__, Pisetsky, E. M. (2019). Using network analysis to identify bridge symptoms between eating disorders and suicidality. Poster at the Annual Meeting of the Eating Disorder Research Society in Chicago, IL. 

17\. Vanzhula, I. A., Christian, C., __Jones, P. J.__, Brosof, L. C., Forbush, K., Smith, K., Tregarthen, J., Farrell, N. A., & Levinson, C. A. (2019). _Replicability of eating disorder psychological networks in five samples: Conceptual and methodological considerations_. Poster at the Annual Meeting of the Eating Disorder Research Society in Chicago, IL. 

16\. Meier, M., Kossakowski, J. J., __Jones, P. J.__, Riemann, B. C., & McNally, R. J. (2019). _The network structure of obsessive-compulsive symptoms in patients with eating disorders_. Poster at the World Congress of Behavioural and Cognitive Therapies, Berlin, Germany.

15\. __Jones, P. J.__*, Heeren, A., & McNally, R. J. (2019). _Beyond symptoms: Why diagnostic criteria are not enough for network analysis_. Symposium at the International Conference for Psychological Science, Paris, France. 

14\. __Jones, P. J.__*, Ma, R., & McNally, R. J. (2019). _Depression comorbidity: Applying bridge centrality in networks to understand overlap with other mental disorders_. Symposium at the International Conference for Psychological Science, Paris, France. 

13\. __Jones, P. J.__*, Simon, T., Zeileis, A., & Mair, P. (2019). _Breaking the assumption of group homogeneity in networks: partitioning networks with machine learning_. Symposium at the International Conference for Psychological Science, Paris, France. 

12\. __Jones, P. J.__, McNally, R. J. (2019). _Do the ever-expanding definitions of violence and trauma contribute to PTSD? Evidence for the trauma treadmill_. Symposium at the International Conference for Psychological Science, Paris, France. 

11\. Bellet, B. W., __Jones, P. J.__, & McNally, R. J. (2019). _Trigger warning: Empirical evidence ahead_. Symposium at the International Conference for Psychological Science, Paris, France. 

10\. __Jones, P. J.__*, Elliott, H., & Schmidt, U. (2018). _Anorexia core symptoms predict poor prognosis: A network analysis in a randomized-controlled trial_. Symposium at the Association for Behavioral and Cognitive Therapies (ABCT) Convention, Washington, DC.

9\. __Jones, P. J.__, Simon, T., Zeleis, A., & Mair, P. (2018). Model-based recursive partitioning of network models: A statistical learning approach to network analysis. Symposium at the Association for Behavioral and Cognitive Therapies (ABCT) Convention, Washington, DC.

8\. Summers, B. J., Aalbers, G, __Jones, P. J.__, McNally, R. J., Phillips, K. A., Wilhelm, S., (2018). _A network perspective on body dysmorphic disorder and major depressive disorder_. Symposium at the Association for Behavioral and Cognitive Therapies (ABCT) Convention, Washington, DC.

7\. __Jones, P. J.__, & McNally, R. J. (2018). _The trauma treadmill: A paradox of PTSD vulnerability_. Symposium at the Heterodox Psychology Conference, Orange, CA.  

6\. Bellet, B. W., __Jones, P. J.__, & McNally, R. J. (2018). _Trigger warning: Empirical evidence ahead_. Symposium at the Heterodox Psychology Conference, Orange, CA.  

5\. __Jones, P. J.__, Ma, R., & McNally, R. J. (2018). _Bridge centrality: Identifying bridge symptoms in psychopathology networks_. Symposium at the Association for Psychological Science Conference, San Francisco, CA.  

4\. Bellet, B. W., __Jones, P. J.__, Neimeyer, R. A., & McNally, R. J. (2018). _Bereavement outcomes as causal systems: A network analysis of the co-occurrence of complicated grief and posttraumatic growth_. Symposium at the Association for Psychological Science Conference, San Francisco, CA. 

3\. __Jones, P. J.__, McNally, R.J., Mair, P., Mugno, B.L., Riemann, B.C. (2017). _Bayesian networks: A directed-acyclic graph approach to comorbid OCD and depression_. Poster presentation at the Association for Behavioral and Cognitive Therapies, San Diego, CA. 

2\. __Jones, P. J.__, McNally, R.J., Mair, P., Mugno, B.L., Riemann, B.C. (2017). _A network perspective on comorbid OCD and depression in adolescents_. Symposium at the Association for Psychological Science Conference, Boston, MA.

1\. __Jones, P. J.__, Heeren, A., McNally, R. J. (2017). _Casting a wider net: Towards a complete network model of psychopathology_. Poster presentation at the Harvard University Mind, Brain, and Behavior Showcase. 

<!-- __Jones, P. J.__, Lefevor, G. T. (2016). _Does social support moderate the effect of external stressors on college student anxiety?_ Poster presentation at the Utah Psychological Association Annual Meeting, Salt Lake City, UT. -->

<!-- __Jones, P. J.__ & Lefevor, G. T. (2016). _Anxiety in college students: Implications from the CCMH database._ Poster presentation at the Mary Lou Fulton Mentored Student Research Conference, Brigham Young University, Provo, UT. -->

<!-- __Jones, P. J.__ (2015). _Casualidad Planeado: Desarollo de Carreras en un Mundo Transitorio._ Oral presentation at the Faculty Conference at Universidad Peruana Simon Bolivar in Lima, Peru. -->

<!-- __Jones, P. J.__ & Livingstone, J. (2015). _Psychological Testing of Social Skills._ Poster presentation at Mary Lou Fulton Research Conference, Brigham Young University, Provo, UT. -->

<!-- __Jones, P. J.__ (2015). _Desarollo de Carreras en un Mercado Global (Career Development in a Global Market)_. Oral presentation at the Brigham Young University Research Conference for the Peruvian Consulate, Provo, UT. -->

<!-- __Jones, P. J.__ (2015). _Career Developmental Resources in Brazilian Society (Recursos de Desenvolivmento de Carreira no Brasil)._ Symposium presentation at the Inquiry Conference, David M. Kennedy Center for International Studies, Provo, UT. -->

# JOURNAL ARTICLES UNDER REVIEW

3\. Goh, P., Martel, M., __Jones, P. J.__, Bansal, P., Eng, A., Elkins, A., Melina, T., & Barkley, R. (in review). Clarifying relations between ADHD and functional impairment in adulthood: Utilization of network and machine learning approaches. 

2\. Wasil, A., Gillespie, S., Park, S. J., Venturo-Conerly, K. E., Osborn, T. L., DeRubeis, R., Weisz, J. R., & __Jones, P. J.__ (in review). Which internalizing symptoms are most strongly associated with happiness? A network analysis of Indian and Kenyan adolescents.

1\. Venturo-Conerly, K. E., Wasil, A., Osborn, T. L., Weisz, J. R., & __Jones, P. J.__ (in review). Depression and anxiety symptoms and social support among Kenyan adolescents: A network analysis.

<!-- 1\. Vanzhula, I. A., Christian, C. __Jones, P. J.__, Brosof, L. C., Forbush, K., Smith, K., Tregarthen, J., Farrell, N. A., & Levinson, C. A. (in review). Replicability of eating disorder psychological networks in five samples: Conceptual and methodological considerations. -->

# GRANT REVIEWER FOR:

* NWO (Netherlands Organisation for Scientific Research)

# JOURNAL REVIEWER FOR:

* Psychological Review
* JAMA Psychiatry
* Psychometrika <!-- 3 -->
* Psychological Methods <!-- 2 -->
* Clinical Psychological Science <!-- 3 -->
* Psychotherapy and Psychosomatics
* Psychological Medicine <!-- 5 -->
* Emotion
* Behaviour Research and Therapy
* Journal of Traumatic Stress
* Journal of Affective Disorders <!-- 2 -->
* Journal of Child Psychology and Psychiatry <!-- 4 -->
* Perspectives in Psychological Science
* Psychological Trauma: Theory, Research, Practice, and Policy
* Frontiers in Psychology <!-- 2 -->
* Archives of Suicide Research <!-- 2 -->
* International Journal of Methods in Psychiatric Research <!-- 3 -->
* European Journal of Psychotraumatology
* Journal of Rational-Emotive & Cognitive Behavior Therapy
* SAGE Open

<!-- _* = 5 or more reviews_ -->

# CLINICAL EXPERIENCE

__Student Therapist__ \hfill May 2019 - Present | Boston, MA   
Center for Anxiety and Traumatic Stress Disorders, Massachusetts General Hospital

* Deliver individual therapy to individuals with traumatic stress and anxiety disorders
* Trained in delivering evidence-based protocols including the UP, PE, CPT, and CBT for SAD & panic
* Administer and interpret diagnostic assessments (SCID, MINI)

__Student Therapist__ \hfill Aug. 2018 - May 2019 | Belmont, MA   
Behavioral Health Partial Hospitalization Program, McLean Hospital

* Provided care to a diverse patient base with wide degrees & forms of psychopathology in an intensive setting
* Performed diagnostic assessments (MINI) and formulate case conceptualizations
* Led six different DBT & CBT-based therapy groups

__Student Therapist__ \hfill June 2017 - Aug. 2018 | Belmont, MA  
Obsessive-Compulsive Disorder Institute, McLean Hospital

* Provided evidence-based individual therapy for obsessive-compulsive and anxiety disorders
* Administered psychological assessments and wrote comprehensive reports (SCID, PID, MoCA)
* Led group therapy sessions focused on managing intrusive thoughts

__Career Counseling Paraprofessional__ \hfill	May 2014- June 2015 | Provo, UT  
Brigham Young University Career and Counseling Center

* Administered career counseling to more than 100 students, both supervised and unsupervised in a peer mentor role
* Received training under a licensed career counselor

<!-- __Youth Counselor__	\hfill	May, 2011- September, 2011 | Seattle, WA  
Boy Scouts of America: ScoutReach Initiative

* Supervised, mentored, and counseled about 80 troubled youth ages 6-10
* Participated in outreach contacting and recruiting groups in low-income neighborhoods -->

# TEACHING & MENTORING EXPERIENCE

<!-- __Student Mentor__ \hfill Oct. 2017 - Present | Cambridge, MA
ZLR Valeon

* Provide face-to-face mentorship to undergraduate students applying to graduate programs in psychology
* Successfully tailor applications to top programs
* Advise students in specific research areas -->

__Teaching Fellow: Psychometrics in R (Graduate)__ \hfill Aug. 2019 - Present | Cambridge, MA  
Harvard University

* Taught sections of an advanced graduate-level course in psychometrics
* Designed and graded problem sets in R
* Taught tutorials on IRT, PCA, multidimensional scaling, network analysis, optimal scaling, and more

__Teaching Fellow: Abnormal Psychology__ \hfill Jan. 2019 - May 2019 | Cambridge, MA  
Harvard University

* Instructed sections of an undergraduate course in Abnormal Psychology 
* Taught sections on depression, anxiety disorders, trauma, behavioral addiction, and suicide

__Psychology Concentration Advisor__ \hfill Apr. 2017 - Apr. 2018 | Cambridge, MA  
Harvard University

* Provided academic and career counseling to undergraduate psychology students
* Worked in collaboration with professional advisers and student advocacy groups

__International School Psychology Intern__ \hfill	Apr. 2015- Aug., 2015 | Lima, Peru  
Colegio Brigham Young School

* Performed one-on-one interventions for students suffering from attention and learning disabilities
* Crossed cultural barriers by immersion in the Peruvian educational system, communicating exclusively in the Spanish language

__Teaching Assistant__	\hfill	May, 2014- June, 2015 | Provo, UT  
Brigham Young University, Department of Student Development

* Taught an undergraduate career development course
* Provided personalized feedback for personality and career testing

__Peer Mentor__	\hfill	April, 2014- September, 2014 | Provo, UT  
Brigham Young University Freshman Mentoring

* Gave personal counseling and assistance to 51 new university students in a peer mentor role
* Provided leadership in student orientation and other large group activities

# DATA SCIENCE EXPERIENCE

__Data Scientist__		\hfill May, 2020 - Present | Boston, MA    
Pluralsight
<!-- * Worked with big data (>2 billion data points) -->

* Develop algorithmic solutions for adaptive skill assessment, recommendation engines, and personalized learning
* Create model prototypes and build interactive applications to demonstrate novel solutions to problems
* Analyze user behavior to provide data-based solutions to business and strategic problems

__Data Scientist__		\hfill November, 2019 - December, 2020 | Cambridge, MA    
Hyka Therapeutics

* Manage data structures, collection, and strategic data analysis for a quickly-growing health startup
* Develop psychometric and digital phenotyping algorithms for digital therapeutics
* Design a smartphone-based data visualization platform for users

# RESEARCH EXPERIENCE

__Graduate Student__		\hfill September, 2016 - May, 2021 (exp.) | Cambridge, MA  
Harvard University, Dr. Richard McNally 

* Research the etiology of psychopathology via network analysis and other quantitative approaches
* Collaborate with leading scholars to advance the field of clinical psychology
* Examine cognitive and social vulnerabilities to emotional disorders

__Research Assistant__		\hfill December. 2015- August, 2016 | Provo, UT  
Brigham Young University, Dr. Tyler Lefevor

* Published first-authored peer-reviewed articles and presented at conferences on the topics of positive psychology interventions, sexuality, and anxiety in college students
* Wrote literature reviews and collaborated on multiple projects with peers
* Conducted and interpreted statistical analyses

__Research Assistant__	\hfill	January, 2015- August, 2016 | Provo, UT  
Brigham Young Univeristy, Dr. Bruce Brown, Associate Chair

* Analyzed statistical data using SAS, SPSS, R, and STATA
* Performed a wide variety of psychometric and regression-based analyses
* Utilized and evaluated statistical techniques for the prediction of ethical behavior

__Research Assistant__	\hfill	May, 2014- June, 2015 | Provo, UT  
Brigham Young Univeristy, Alberto Puertas

* Assisted in research concerning emerging career counseling models
* Wrote new curriculum for a career development course focusing on narrative approaches to career decision

<!-- 
# VOLUNTEER & LEADERSHIP 

__Psi Chi Presidency__	\hfill	September, 2015- Present | Provo, UT  
Psi Chi International Honor Society 

* Managed logistics for an organization of more than 75 members
* Planned and conducted events to promote academic and career achievement in the psychology department
vCollaborated with university administration and faculty to provide extracurricular opportunities for students

__Student Outreach Council__ \hfill	September, 2015- Present | Provo, UT  
Brigham Young University Counseling and Psychological Services

* Organized events and activities to promote positive mental health practices among university students
* Educated peers about mental health stigma and how to seek proper treatment for psychological dysfunction 
* Promoted the correct treatment of mental disorders through social media

__Vocational Rehabilitation Technician__ \hfill	Jan., 2015- June, 2015 | Provo, UT  
Utah State Hospital, Forensic Unit

* Trained 12 mental health patients in vocational skills necessary for rehabilitation
* Provided educational support for patients working toward the completion of general education degree and technical degree requirements
* Aided staff in supervision and monitoring of suicidal and dangerous behavior

__Full-time Service Volunteer__	\hfill Oct., 2011- Oct., 2013 | Vitoria, Brazil  
The Church of Jesus Christ of Latter-Day Saints

* Managed 26 other volunteers during a full-time 2-year service mission
* Immersed in Brazilian culture, including more than 11 months with limited contact with other Americans
* Assisted individuals in addiction recovery and resolution of familial problems

# AWARDS & HONORS

__Top 25 Reviewer__ \hfill Sep. 2019
The Journal of Child Psychology and Psychiatry

__Sigma Xi Nomination__ \hfill July 2018  
Sigma Xi Scientific Research Honor Society

__Graduate Research Fellowship__ \hfill April 2018  
National Science Foundation (NSF-GRFP)

__Student Poster Excellence Award__ \hfill November 2017  
Association for Behavioral & Cognitive Therapies - Anxiety Disorders

__Karen Stone Fellowship__ \hfill	September 2016    
Harvard University

__Valedictorian__	\hfill	April 2016  
Department of Psychology, Brigham Young University

__Mastery Level Certification: Portuguese__ \hfill	April 2015  
American Council for the Teaching of Foreign Languages

__Phi Cappa Phi National Honor Nomination__	 \hfill February 2015  
Phi Cappa Phi National Honor Society

__Golden Key International Honour Nomination__	\hfill December 2014  
Golden Key International Honour Society

__National Merit Scholar Award__	\hfill September 2011  
National Merit Scholarship Corporation

__BECU National Scholarship__ 	\hfill October 2011  
Boeing Employees Credit Union

__Heritage Scholarship__	\hfill August 2011  
Brigham Young University

-->

# LANGUAGE & INTERNATIONAL EXPERIENCE

__Brazilian Portuguese__	\hfill July 2011- Present  
Bilingual Proficiency

* Lived in Espirito Santo, Brazil from December 2011 to October 2013
* Lived without English contact from November 2012 to October 2013
* Mastery Level Certification from the American Council for the Teaching of Foreign Languages

__Spanish__		\hfill April 2015- Present  
Professional Proficiency

* Lived in Lima, Peru from April 2015 to August 2015
* Presented an academic presentation at a university conference in Lima, Peru
* Presented an academic presentation to the Peruvian consulate of Utah 
